### ISSUE TITLE
Cannot find *.bin pretrained models

### ISSUE THREAD

**Issue by r4ghu** [tbennun/cudnn-training#12]
"You can also use the pre-trained weights published along with CUDNN, using the "pretrained" flag."
Hi,
First of all, thanks for writing this code using CuDNN and CuBLAS. It will be helpful for my current project. In your code, you initialised a flag named 'pretrained' if we want to use a pre-trained model. I generated a model using theano in python and stored it as a .pkl file. Now, I want to import it into the present code as pretrained model. I would like to know in what structure are you storing the network in .bin format and importing it. (I couldn't find any .bin files in your repository). Any suggestions related to this issue are appreciated!

**Comment by tbennun** [comment]
The format that I used is the CUDNN example .bin files, which are included in their website. This was meant for verification that the sample works. The format is very simple and hardcoded:

``` cpp
    // Determine initial network structure
    if (FLAGS_pretrained)
    {
        conv1.FromFile("conv1");
        conv2.FromFile("conv2");
        fc1.FromFile("ip1");
        fc2.FromFile("ip2");
    }
```

For each layer, there are two .bin files with matching name (conv1.bin, conv1.bias.bin, ..., ip2.bin, ip2.bias.bin). Each file is actually the weights and biases (float32) in binary format, without any headers. For more details, see the FromFile functions at https://github.com/tbennun/cudnn-training/blob/master/lenet.cu#L163 and 
https://github.com/tbennun/cudnn-training/blob/master/lenet.cu#L211

**Comment by r4ghu** [comment]
Any suggestions on how to convert a network in .pkl format created using theano in python to .bin files (or) reading them directly in cpp?

**Comment by tbennun** [comment]
I don't know the .pkl format, but I suggest to try to manually obtain the weight/bias matrices from each layer and save them in binary format (use Python's `file.write` and `struct.pack`)

**Comment by tbennun** [comment]
Since this is out of the scope of this project, I'm closing this issue.

Good luck!
