### ISSUE TITLE
Succesfully compiled, but can't make it read the MNIST data

### ISSUE THREAD

**Issue by goldenageofballooning** [tbennun/cudnn-training#13]
$ ls -al
drwxrwxr-x 3 username username     4096 Nov  4 18:49 .
drwxrwxr-x 5 username username     4096 Nov  4 18:49 ..
-rw-rw-r-- 1 username username    19476 Nov  4 17:29 CMakeCache.txt
drwxrwxr-x 5 username username     4096 Nov  4 17:29 CMakeFiles
-rw-rw-r-- 1 username username     1409 Nov  4 17:29 cmake_install.cmake
-rw-rw-r-- 1 username username     5006 Nov  4 17:29 Makefile
-rw-rw-r-- 1 username username  7840016 Nov  4 18:49 t10k-images.idx3-ubyte
-rw-rw-r-- 1 username username    10008 Nov  4 18:49 t10k-labels.idx1-ubyte
-rw-rw-r-- 1 username username 47040016 Nov  4 18:49 train-images.idx3-ubyte
-rw-rw-r-- 1 username username    60008 Nov  4 18:49 train-labels.idx1-ubyte
-rwxrwxr-x 1 username username   765712 Nov  4 17:29 trainlenet
$ ./trainlenet 
Reading input data
ERROR: Cannot open image dataset train-images-idx3-ubyte
ERROR: Cannot open image dataset t10k-images-idx3-ubyte

Clearly the training and the test data are in the same folder with binary but somehow it doesn't see them.

Could you help?

Best,
C.

**Comment by tbennun** [comment]
Yes, the problem is that the files are called "t10k-images.idx3-ubyte" and the program is looking for "t10k-images-idx3-ubyte". There is a dot instead of a hyphen before the "idx3" in all four files.

Good luck!

**Comment by goldenageofballooning** [comment]
Thanks a lot!
