### ISSUE TITLE
OpenCL compilation possible now :-)

### ISSUE THREAD

**Issue by hughperkins** [tbennun/cudnn-training#18]
Hi Tal Ben-Nun,

This is not an issue, it's just for information: using cuda-on-cl, https://github.com/hughperkins/cuda-on-cl, I think it is now more or less possible to build and run your cudnn-training code, on an OpenCL device, without needing CUDA Toolkit etc.  Simply needs some small changes to the CMakeLists.txt  https://github.com/tbennun/cudnn-training/compare/master...hughperkins:opencl

(I was/am using your code as a test bed for writing the cuda-on-cl compiler :-) )

**Comment by tbennun** [comment]
Thanks for letting me know, and CUDA on CL looks like an interesting project. :)

From the code, it seems that multi-GPU support is not included (otherwise, the code is identical). Why is that? It is certainly possible, given your EasyCL implementation.

**Comment by hughperkins** [comment]
Ah, good point. Actually, that was because I was validating the device number against the total number of devices, which I was doing by polling the number of platforms/devices each call.

I've cached the total number of devices now, https://github.com/hughperkins/cuda-on-cl/commit/d35593fc04cad902092de220fb1ea135ee198795 and uncommented the setDevice lines https://github.com/hughperkins/cudnn-training/commit/9cceece3963926eca2490c9754aa5af2320f7fcb .

**Comment by tbennun** [comment]
OK, great. So now, apart from some documentation and printouts, there are no modifications to the code. Nice 👍

**Comment by tbennun** [comment]
As for the CUDA-on-CL project, I wonder how it fares with more complex kernels. Are you familiar with [MAPS](https://github.com/maps-gpu/MAPS)? It's a nice project that aims to simplify GPU programming by defining a set of common memory access patterns, and accessing memory using index-less foreach loops (hiding away shared memory, vectorization and other optimizations).
I always thought that an OpenCL version would be nice but implementing that could take a while. Do you think your projects can be used for running it on OpenCL 1.2 devices?

**Comment by hughperkins** [comment]
I wasnt aware of MAPS. I'll take a look. Thank you for the heads-up :-)

As far as other kernels, cuda-on-cl can build a bunch of Eigen/Tensorflow kernels, eg some unit tests for building some eigen kernels https://bitbucket.org/hughperkins/eigen/branches/compare/hughperkins/eigen:tip%0Deigen/eigen:default#diff , and a tensorflow fork that runs partially on opencl using cuda-on-cl https://github.com/hughperkins/tensorflow-cl/compare/master...tensorflow-cl?expand=1

**Comment by hughperkins** [comment]
Update: cudnn-training runs ok on Mac Sierra, using Radeon Pro 450, now :-)
