### ISSUE TITLE
Cannot compile under Mac

### ISSUE THREAD

**Issue by kwccoin** [tbennun/cudnn-training#19]
make
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/ext2int2adm/minst-minist/build
[ 33%] Building NVCC (Device) object CMakeFiles/trainlenet.dir/trainlenet_generated_lenet.cu.o
/Users/ext2int2adm/minst-minist/lenet.cu(438): error: too few arguments in function call

/Users/ext2int2adm/minst-minist/lenet.cu(438): error: too few arguments in function call

2 errors detected in the compilation of "/var/folders/_p/rprk3ny52js8t0frzdn3strc0000gn/T//tmpxft_00014fe8_00000000-11_lenet.compute_50.cpp1.ii".
CMake Error at trainlenet_generated_lenet.cu.o.cmake:278 (message):
  Error generating file
  /Users/ext2int2adm/minst-minist/build/CMakeFiles/trainlenet.dir//./trainlenet_generated_lenet.cu.o

make[2]: *** [CMakeFiles/trainlenet.dir/trainlenet_generated_lenet.cu.o] Error 1
make[1]: *** [CMakeFiles/trainlenet.dir/all] Error 2
make: *** [all] Error 2

**Comment by tbennun** [comment]
Which version of CUDNN are you using?

**Comment by tbennun** [comment]
Now resolved, see PR #23
