### ISSUE TITLE
Compile cudnn-training

### ISSUE THREAD

**Issue by yasilvalmeida** [tbennun/cudnn-training#2]
Hi 

I have some problems compile in VS2013. I got this error:

Error   1   error : argument of type "cudnnAddMode_t" is incompatible with parameter of type "const void *" D:\cudnn-training\lenet.cu  cudnn-training

**Comment by tbennun** [comment]
The code was tested with CUDNN v2. Since then (in CUDNN v4), the API was modified.
Will be corrected.

**Comment by tbennun** [comment]
Thanks to @AdamSLevy, Pull Request #6 should provide a temporary solution until cuDNN v4 is implemented.

**Comment by tbennun** [comment]
Resolved in the latest commit.
