### ISSUE TITLE
Error while make execution

### ISSUE THREAD

**Issue by akshit-sharma** [tbennun/cudnn-training#22]
The program is generating an error while executing make command. It says 
`cudnn-training/lenet.cu(438): error: too few arguments in function call`

I am using cudnn 6 with CUDA 8 on Ubuntu 16.04.
After a few digging some results on the google search, I figured that parameters of cudnnSetConvolution2dDescriptor function have changed for version 6 of cudnn from 8 arguments to 9 arguments.

[source](https://github.com/BVLC/caffe/pull/5478/files) for above conclusion.

**Comment by tbennun** [comment]
CUDNN 6 is not supported yet. I'll update it when I get the chance, but if you get it to work properly on CUDNN 6, please upload a pull request.

**Comment by akshit-sharma** [comment]
I have successfully compiled it using cudnn v6. I am sending you a pull request.

**Comment by tbennun** [comment]
Thanks! Closing this issue.
