### ISSUE TITLE
compile errors and excute errors

### ISSUE THREAD

**Issue by zhongtao93** [tbennun/cudnn-training#3]
I find VS can't compile this 2 sentences:
// Disable copying
TrainingContext& operator=(const TrainingContext&) = delete;
TrainingContext(const TrainingContext&) = delete;
And I choose to annotation them, then I can compile successfully. I don't know if these two sentences are necessary.
However, when I debug it, there is a error, is about test images function, locate at line 486 in lenet.cu, error is CUDNN_STATUS_EXECUTION_FAILED at cudnnConvolutionForward(), I look up the document and it means the function failed to launch on the GPU, I don't know why, it is connected with annotation those two sentences? Really hope you can reply it ,thank you very much!
This is output:
![error](https://cloud.githubusercontent.com/assets/15263824/14015128/caf1c508-f1f1-11e5-9630-8aa2fdfebe1c.jpg)

**Comment by zhongtao93** [comment]
Ok, I fix it, the reason is that the test images batch_size=1, that's is too small, and I change it to 64, then can run successfully. Anyway, thank you very much!

**Comment by tbennun** [comment]
OK, good to know. 
I will remove those two " = delete" lines (as they are unrelated to the functionality of the code) in the next version, which will support CUDNN v4.
